version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 63306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxx
